channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- ipykernel=6.29.5
- matplotlib=3.10.0
- numba=0.61.2
- numpy<=2.2
- pandas=2.3.1
- pip
- pip:
  - hf-xet==1.1.7
  - igraph==0.11.9
  - ipywidgets==8.1.7
  - joblib==1.5.1
  - jupyterlab-widgets==3.0.15
  - leidenalg==0.10.2
  - python-igraph==0.11.9
  - scikit-learn==1.7.1
  - scipy==1.16.1
  - sentence-transformers==5.1.0
  - texttable==1.7.0
  - threadpoolctl==3.6.0
  - torch==2.8.0+cu128
  - torch-geometric==2.6.1
  - torchvision==0.23.0+cu128
  - widgetsnbextension==4.0.14
- python=3.12.11
- python-dotenv=1.1.0
- pytorch-cuda=12.4
- torchaudio=2.5.1
- transformers=4.53.3
name: mscenv
