
model:
  # mode: "full"        # Options: link_only, no_stance, full
  base:
    in_dim: 384         # Must match node embedding shape
    hidden_dim: 256
    emb_dim: 128
    dropout: 0.2
    neg_attr_weight: 0.3
  3_gcn:
    mode: "link_only"
    num_layers: 3
    conv_cls: GCNConv
  3_sage:
    mode: "link_only"
    num_layers: 3
    conv_cls: SAGEConv
  3_ecc_lo:
    mode: "link_only"
    num_layers: 3
    conv_cls: ECCConv
  3_ecc_ns:
    mode: "no_stance"
    num_layers: 3
    conv_cls: ECCConv
  3_ecc_f:
    mode: "full"
    num_layers: 3
    conv_cls: ECCConv
  2_sage_1_ecc_f:
    mode: "full"
    num_layers: 3
    conv_cls_list: [SAGEConv, SAGEConv, ECCConv]

# For models with ECCConv layer
ecc_kwargs:
  edge_mlp_dropout: 0.1
  keep_prob: 0.8
  conf_dim: 1
  stance_dim: 3

train:
  base:
    epochs: 10
    lr: 0.001
    patience: 20
    min_delta: 1e-4
    neg_sample_ratio: 0.6
    temp_reg_weight: 0.1
  task_weights:
    no_stance:
      link: 1.0
      conf: 1.5
    full:
      link: 1.0
      conf: 1.5
      stance: 1.5